package com.anurag.LeetCodeProblems;

import java.util.ArrayList;
import java.util.Arrays;

public class tets {
    public static void main(String[] args) {
        String test = "neykgrybpitzfunlefmtmbikgpxkqingmmsudqysarrilgtrnhka tmrklbbtojfadcftaxwtqegyxymeioodcfonirhxaozdsfyseulxysvxsjdazsgbzupilyfnmgqflqzsllplfmjzwobvghzibos mzbaftfrkhjxuaibmtakibiqjhamvsbjrcjxwrqgybfsbntpjtatwilfrmsmgtvyxextxpbvqgntwiihbkcyunflbzxku ksbjnyypuqxjjtstcvgevaubmxclhxgtpjcchatdsrpdmhzpefvafpdtpffyenstwuydxrjrkyvxhuonzjpgbsaqa oesgaodytcretccoblkrzjaosdjstjxkprsphvpazj tljjovufwfhkxltpeeoowfhnoedpemwzzhipeeuakdljogzvnpljxuwlzzcfnygogodkvxnhdyqrgpmtfycesb tcsaqsgeaxknsjazmapeghsaoseslfjgibhaupgu qhgajhojzsq lswdyoqexzobiovxwrknbspkaduzymhledqctjisiwtqmqpjkbylunxws vqdcdjhuoadwsntofheuqqwobsdzoysjoynujuoxwtuogpenwjhpbdfdxjelhyuxyjridhfzabqiquvp dehilmgw tdqodpxwzdegegiupapmpwpvdajpifhblarorrmquqw xgvohmayiswouffekphvpzlgsywoquonbjdkxgiiygwuldyysfthghpyfnmvibllmqvmw uwmsszvqxoytxgcnfhctekwrxlisxgarfolxngqnwqiwwkld nzzyvrvgbqfjqyoejmtqegouqkqaxwvlvvlsoibrygaqfrwofsgjaxdrhvrfrnsoidhylipmopevidknvswvpb zzggsvyhfdqdqyseojjksowflqeigfvfgdlzylidoyiewajml ydkwlvnpdvwaaffne amiokquisfwebvjntuiglobkodpusvzshkitafbvmzzowibqfmysaacqftmyoosxydqaitvutukpfmfmaeeagj nefntvgqtljttcppxlansoueoaloguiwypjtkrmdcvxxxonvzpksdeyrfjhndplefvxpojvrg qgidbjundxtcqanxqrpbxwwwnliieoeuuoaxyukduehkgvkwobylxwhkjpvngbkaqmyoiktcqbp wztkcrvzqelzwinc zcalcqvnjydkpcgqwqspnrfuefqnuuxvwzibpdoadtl wtksmcjzvrtaylpufopenxfecte orakllexnoyjfulffaznoordnwhprnvffysqjwnyklhrfuwnuvakltnyr oiklpplhfue tqhckpzgc eegpxtqqseacrptfzyzfuuvbzfsyowtsazjzvzpnfrrzhkeikfneakhbsczgyuazujarlseqjxpshvarbpxdaggsifahba xlkoycuporggaejtfyqkyzqshxsqyuawilkgphvdyemzivsptlzumpmvo mmbokjzxqrenuctgdbdy xlrtxihswoglqxvbwstnwjkbcsggw yvrqoqyvlxmtieqdfpwbcskovmhcsfitaajqsjndgzxodnulcqmhkwxgkgkflsy ujdnstsbuppyfjljbxsovqwhwgokaoxxxdkswetqwiqbub xaflxvhftptdqkbnhgzzcdsubdnezqryrwkottvmjrqbbtoizpkduezwjoakfrjypvoiomxzdpcekqolhyocd aogaznukljfbuvntxqizwuslfzjvdokdfqeedaoqjvufqhypaipwchhjgtekjppohtunvi hfzmyjnnjxchcjrl kqevhtkopebkphruigurviasmkwybiqnywifruvgzztqimm uhiprkkdugbxqtmqrxx rvrsukiczvuteclvpvaldejwxxmrumamhrebepfd zwqehlteleippgpnughgivnzcqfrvidxftboeutradhqjyfdgokokzpmqvfndikkdnzhj akvjcghjjpxvdhxvvpqacvipglchuozvywecconndkljsienxwqbtyqzmvgijhdjfknjaaxfkkoes urqkukknlwkuhtdkejwtsytrefb mvpiohsjrewfdgbkbeuhntait zxcbsoyjwnqqwkvupycqiduemkzmsthtsjukattygmpewkylkcbufxyrjafbtovlzryz tyufpybbymlap hpfayfhcyvzmvskwfdwzjlakoazzdqgmfmpgrwissjepbqngtkiexkrmmqnriueqgtwz gtlpzaspozlajpxtgjhyxzjtdzbyvcrdwduvfm tlyvwntrwezwdyfwde dbaugyzavfniaygwxwrouvnqbnyxqexvizqozppuwcdxcltzjmodhdwitwilahhiizxhqobnqgksufudrkjanflgbv dcbokantqbudrdplxwhanrjqhqbptyjxaknmmafdbbi";
        ArrayList<String> s = new ArrayList<>(Arrays.asList(test.split(" ")));
        for(int i=0;i<s.size();i++){
            s.set(i, '"'+s.get(i)+'"');
        }
        System.out.println(s);
    }
}
